---
title: "Transform"
output: html_document
date: "2023-06-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)

# 设置工作目录为当前文件夹
setwd(".")

# 判断是否存在data_csv文件夹，如果不存在就创建该文件夹
if (!dir.exists("data_csv")) {
  dir.create("data_csv")
}

# 构建文件路径
file_path <- file.path("data_xlsx", "USDCNY.xlsx")
USDCNY <- read_xlsx(file_path)
output_path <- file.path("data_csv", "USDCNY.csv")
write.csv(USDCNY, output_path)

file_path <- file.path("data_xlsx", "USDCNH.xlsx")
USDCNY <- read_xlsx(file_path)
output_path <- file.path("data_csv", "USDCNH.csv")
write.csv(USDCNY, output_path)

file_path <- file.path("data_xlsx", "CSI300.xlsx")
CSI300 <- read_xlsx(file_path)
output_path <- file.path("data_csv", "CSI300.csv")
write.csv(CSI300, output_path)

file_path <- file.path("data_xlsx", "USDX.xlsx")
USDX <- read_xlsx(file_path)
output_path <- file.path("data_csv", "USDX.csv")
write.csv(USDX, output_path)

file_path <- file.path("data_xlsx", "SPX.GI.xlsx")
SPX.GI <- read_xlsx(file_path)
output_path <- file.path("data_csv", "SPX.GI.csv")
write.csv(SPX.GI, output_path)
```